version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:node12.13.0-chrome80-ff74
        environment:
          TERM: xterm
    working_directory: ~/root

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages

      - run:
          name: Environment
          command: |
            node --version
            npm --version
            yarn --version
      - run:
          name: Installing dependencies
          command: yarn
      - save_cache:
          name: Saving package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Running tests
          command: yarn test
